<?php

namespace emagine\ComBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WikiPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WikiPageRepository extends EntityRepository
{
}
