emagine_com_wikipage:
    resource: "@emagineComBundle/Resources/config/routing/wikipage.yml"
    prefix:   /wikipage

emagine_com_homepage:
    path:     /ca/communication
    defaults: { _controller: emagineComBundle:Default:index }

emagine_com_charte:
    path:     /com/charte
    defaults: { _controller: emagineComBundle:Default:charteGraphique }