<?php

namespace emagine\SecGBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdhesionCheckerCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhesionCheckerCategoryRepository extends EntityRepository
{
}
