<?php

namespace emagine\SecGBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdhesionCheckerCat‚goriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhesionCheckerCat‚goriesRepository extends EntityRepository
{
}
