wikipage:
    path:     /
    defaults: { _controller: "emagineComBundle:WikiPage:index" }

wikipage_new:
    path:     /new
    defaults: { _controller: "emagineComBundle:WikiPage:new" }

wikipage_create:
    path:     /create
    defaults: { _controller: "emagineComBundle:WikiPage:create" }
    methods:  POST

wikipage_markdown_parser:
    path:     /markdown
    defaults: { _controller: "emagineComBundle:WikiPage:markdown" }

wikipage_edit:
    path:     /{id}/edit
    defaults: { _controller: "emagineComBundle:WikiPage:edit" }

wikipage_update:
    path:     /{id}/update
    defaults: { _controller: "emagineComBundle:WikiPage:update" }
    methods:  [POST, PUT]

wikipage_delete:
    path:     /{id}/delete
    defaults: { _controller: "emagineComBundle:WikiPage:delete" }
    methods:  [POST, DELETE]

wikipage_show:
    path:     /{slug}
    defaults: { _controller: "emagineComBundle:WikiPage:show" }