emagine_secG_AdhesionChecker_index:
    path:     /ca/AdhesionChecker
    defaults: { _controller: emagineSecGBundle:AdhesionChecker:index }

emagine_secG_AdhesionChecker_add_category:
    path:     /ca/AdhesionChecker/addCategory
    defaults: { _controller: emagineSecGBundle:AdhesionChecker:addCategory }

emagine_secG_AdhesionChecker_show_category:
    path:     /ca/AdhesionChecker/showCategory/{id}
    defaults: { _controller: emagineSecGBundle:AdhesionChecker:showCategory }
    requirements:
        id: \d+